[project]
name = "sky-ie-project"
version = "0.1.0"
description = "Optimization project file of team 2"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "scipy>=1.16.0",
    "stats>=0.1.2a0",
    "tqdm>=4.67.1",
]
